[package]
name = "fruid_cli"
version = "0.0.1"
authors = ["Ethan Mann <emanndev7@gmail.com"]
edition = "2021"

[dependencies]
console = { version = "0.14.1"}
dialoguer = { version = "0.8.0"}
indicatif = { version = "0.16.2"}
